name: Release Herald

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Plugin
        run: dotnet build -c Release -o ./publish
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: The Herald ${{ github.ref_name }}
          files: ./publish/Herald.dll
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
